# ===============================
# CONFIGURACOES DA APLICACAO E SERVIDOR
# ===============================
spring.application.name=diariotreino
server.port=${PORT:8080}

# ===============================
# BANCO DE DADOS (dinamico para nuvem ou local)
# ===============================
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:diario_treino}?serverTimezone=UTC

spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}

# ===============================
# CONFIGURACOES DO HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
