# ===============================
# CONFIGURAÇÕES DA APLICAÇÃO E SERVIDOR
# ===============================
spring.application.name=diariotreino
server.port=${PORT:8080}

# ===============================
# BANCO DE DADOS (Dinâmico para Railway ou Local)
# ===============================
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:diario_treino}?serverTimezone=UTC

spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}

# ===============================
# CONFIGURAÇÕES DO HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
